runtime: nodejs16
env: standard
env_variables:
  ACCESS_TOKEN: wAgVDuBq7BaNyluoKdHDiAsdfkljsfsdakfjdfsfsjjfsfjorywetyrfhdsncvasfsahflkdsfosdhfjfsafhSFSFSFSDFSAFakiljsdflaj
  DB_USER: neo4j
  DB_PASSWORD: orBrMW4g5jcjamPWY9VN345pbWDtk0J6cal2aCIXlPA
  DB_URI: neo4j+s://8e76d565.databases.neo4j.io
